server.port=8080

# --- BASE DE DATOS (NEON.TECH) ---
spring.datasource.url=jdbc:postgresql://ep-restless-mouse-acsmuzud-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_iOQVR5HsYvr7
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- STRIPE INTEGRATION ---
stripe.api.key=sk_test_51T1Y4012wkAy9LpKiV6xcYSteihHJKfluEc0IwbdYzOULpIjaDJxqY3fjcbiQYEmkWxUKL5LtKnMPDvKZ2gnfJIz00S17KhVsE
stripe.webhook.secret=whsec_1f72d28df2d2bf76dc9f7f815e48d88eca44c9bce13f15dc28ae8f21a375cd2f

# --- META CAPI ---
meta.pixel.id=1578432683383723
meta.access.token=EAAXzW89gvt0BQmjtVgj310sQnWiqQGaoPL3k9ZAOosopReAWOB9tZB274OZCIQH7OZCMGc0zIZCLD7G8LavBNCoyidmkZAKb0L5gPmx6KUXDn58OWENMkcR68xqSQVQaEQjqDI0S0TIJlLhliymVMIkiQKmviHN2t6CCHSTROCXzbxAGNFZBq7clHMbxhWB8X38TwZDZD

# --- GOOGLE ADS (NUEVO TOKEN INCLUIDO) ---
google.ads.clientId=529670422058-ptrp8j2qdf4ehoqfsuvag0i8s2cor47l.apps.googleusercontent.com
google.ads.clientSecret=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
google.ads.refreshToken=1//04l21D1MXynYBCgYIARAAGAQSNwF-L9IrUUcacKrxZ7loHH6KOnZa9YFtMDip0HwHtWWtTElef89EaCA8FKz6v2D9RjmF0fkfPlc
google.ads.developerToken=U9ryAeajsJ2EQwP8psbhjQ
google.ads.loginCustomerId=2615968925
google.ads.customerId=2615968925
google.ads.conversionActionId=7523010917

# --- PIPEDRIVE ---
pipedrive.api.token=4388aef3f15d5679ec6ee87f88d587da599e7a92
pipedrive.domain=tu-empresa-sandbox

# IDs de Stripe para Starter
stripe.price.starter.setup=price_123_setup
stripe.price.starter.monthly=price_123_monthly

# IDs de Stripe para Growth
stripe.price.growth.setup=price_456_setup
stripe.price.growth.monthly=price_456_monthly